server:
  port: 9000

spring:
  data:
    mongodb:
      auto-index-creation: true

      uri: mongodb+srv://educ4:Xee6k5svsWsOMNrk@cluster0.pyxqz.mongodb.net/dev-educ4
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG