server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb+srv://educ4:Xee6k5svsWsOMNrk@cluster0.pyxqz.mongodb.net/educ4
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 432269780027-t1ik5162iam7od3t497f72sdbguj1kdc.apps.googleusercontent.com
            clientSecret: Mm2swEBNP9XwCffOoE2C6rPk